### ISSUE TITLE
Error write+execute memory for ffi.callback

### ISSUE THREAD

**Issue by db306** [evertramos/nginx-proxy-automation#205]
# Error description:

When running a clean install, the nginx-letsencrypt container fails outputting this curious error. The stack works, I can make multiple sites work with no issue, however, SSL certificates are not issued. I have tried multiple different configurations without luck.

```
Reloading nginx docker-gen (using separate container nginx-gen)...
Reloading nginx (using separate container e91a3d6b87f7bf8b9caee1514fd2e3bca880a91e1a1748223a58d2490cda1471)...
Creating/renewal portainer.domain.com certificates... (portainer.domain.com)
2020-05-15 14:28:42,806:INFO:simp_le:1359: Generating new account key
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1601, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1585, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1443, in persist_new_data
    client = registered_client(
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1377, in registered_client
    directory = messages.Directory.from_json(net.get(args.server).json())
  File "/usr/lib/python3.8/site-packages/acme/client.py", line 1144, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python3.8/site-packages/acme/client.py", line 1094, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 342, in connect
    self.ssl_context = create_urllib3_context(
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 289, in create_urllib3_context
    context.verify_mode = cert_reqs
  File "/usr/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 438, in verify_mode
    self._ctx.set_verify(_stdlib_to_openssl_verify[value], _verify_callback)
  File "/usr/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1119, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/usr/lib/python3.8/site-packages/OpenSSL/SSL.py", line 337, in __init__
    self.callback = _ffi.callback(

MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks

```

# Steps to reproduce

Run Docker 19.03.8-r1 on Alpine 3.7.0, deploying the docker-compose-letsecrypt-nginx-companion with docker-portainer-letsencrypt or any other package.

# Expected result

This should release ssl certs for each domain submitted

# Error result

No certificates are released

# Comments

This is the current .env configuration for the docker-compose-letsencrypt-nginx-proxy-companion

```
NGINX_WEB=nginx-web
DOCKER_GEN=nginx-gen
LETS_ENCRYPT=nginx-letsencrypt
IP=0.0.0.0
NETWORK=webproxy
NGINX_FILES_PATH=./nginx-data
```

This is the .env configuration for the docker-portainer-letsencrypt

```
CONTAINER_NAME=portainer
PORTAINER_DATA_PATH=/home/db306/portainer/data
ADMIN_PASSWORD=XXXXXXXXX
DOMAINS=portainer.domain.com
MAIN_DOMAIN=portainer.domain.io
LETSENCRYPT_EMAIL=myemail@gmail.com
PORTAINER_SSL_PATH=/home/db306/webproxy/data/certs
PORTAINER_SSL_CERTIFICATE=/certs/$MAIN_DOMAIN.crt
PORTAINER_SSL_KEY=/certs/$MAIN_DOMAIN.key
NETWORK=webproxy
```

Any ideas ?

**Comment by evertramos** [comment]
Please try the new version (v0.5), in case of error open a new issue. Thanks!
