### ISSUE TITLE
Unable to generate certificate via HTTPS

### ISSUE THREAD

**Issue by samip5** [evertramos/nginx-proxy-automation#215]
# Error description:
Unable to renew certs due to an error.

# Steps to reproduce
Have a container that nginx-letsencrypt container tries to generate a certificate for, and have it fail.

# Expected result
Generate certificate

# Error result
```
2020-07-14 14:31:02,313:ERROR:simp_le:1417: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5877324557
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1406, in finalize_order
    finalized_order = client.poll_and_finalize(order)
  File "/usr/lib/python3.8/site-packages/acme/client.py", line 709, in poll_and_finalize
    orderr = self.poll_authorizations(orderr, deadline)
  File "/usr/lib/python3.8/site-packages/acme/client.py", line 733, in poll_authorizations
    raise errors.ValidationError(failed)
acme.errors.ValidationError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1479, in persist_new_data
    order = finalize_order(client, order)
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1433, in finalize_order
    raise Error('Challenge validation has failed, see error log.')
simp_le.Error: Challenge validation has failed, see error log.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1601, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1585, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1495, in persist_new_data
    persist_data(args, existing_data, new_data=IOPlugin.Data(
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1164, in persist_data
    plugin.save(new_data)
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 562, in save
    key = self.dump_key(data.key)
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 460, in dump_key
    return OpenSSL.crypto.dump_privatekey(self.typ, data.wrapped).strip()
AttributeError: 'NoneType' object has no attribute 'wrapped'

Unhandled error has happened, traceback is above
```

# Comments

**Comment by evertramos** [comment]
Please try the new version (v0.5), in case of error open a new issue. Thanks!
